[package]
name = "just-lsp-analysis"
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
just-lsp-analyzer = { workspace = true }
just-lsp-document = { workspace = true }
salsa = { workspace = true }
tower-lsp = { workspace = true }
