[package]
name = "just-lsp-analysis"
version = "0.0.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
just-lsp-analyzer = { workspace = true }
just-lsp-document = { workspace = true }
salsa = "0.24.0"
tower-lsp = { workspace = true }
